
services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-vector.sql:/docker-entrypoint-initdb.d/init-vector.sql:ro
  mongodb:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  n8n:
    build: .
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n
      EXECUTIONS_PROCESS: main
      N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN: "true"
      N8N_DEFAULT_EMAIL: admin@example.com
      N8N_DEFAULT_PASSWORD: changeme
      N8N_DEFAULT_FIRSTNAME: Owner
      N8N_DEFAULT_LASTNAME: User
    depends_on:
      - postgres
      - mongodb
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  postgres_data:
  mongodb_data:
  n8n_data:
